### PR TITLE
feat: add interactions suport

### PR DESCRIPTION
**Pull request by UndiedGamer**
**Please describe the changes this PR makes and why it should be merged:**
This pr adds support for {{interaction}} tags in `tagscript-plugin-discord`

**Status and versioning classification:**
- Code changes have been tested and working fine, or there are no code changes
- This PR changes the library's interface (methods or parameters added)

> **Note**
> Tests needs a rewrite

### CODE REVIEW

**Comment by imranbarbhuiya** [comment]
Thanks. Can you add some tests, please? Also, let me know if you are comfortable with letting me push changes to your fork to add interaction options.

**Comment by UndiedGamer** [comment]
yes, i am comfortable with you pushing changes that let me just add some tests

**Review by imranbarbhuiya — APPROVED** [review]

**Comment by imranbarbhuiya** [comment]
@UndiedGamer Thanks. Btw as I'm busy, I've tested the code in my project, and everything is working fine. Here only to maintain test coverage, I've added some invalid tests. If u r interested then you can change these tests. Else I'll do it after my exam.

**Comment by imranbarbhuiya** [comment]
@all-contributors please add @UndiedGamer for code

**Pull request merged**
